#!/bin/bash
# 2019-07-15 Kyle
# This is a post-checkout hook. so  .git/hooks/post-checkout with execute bit
# PWD is always the git repo
# $1 previous HEAD, $2 now, aka new HEAD, $3 is a flag if a branch has been changed
# cache usually holds copies of nwjs, but maybe no copies of nwjs are present...
BRANCH=$(git branch 2>/dev/null | grep '^*' | colrm 1 2)
# Usually you'd start at zero, not with expr....
HASH=$(expr substr $2 1 9)
mkdir -p cache
echo "{\"gitChangesetId\": \"$BRANCH/$HASH\"}" > cache/version.json
#echo hook $BRANCH/$HASH
